[package]
name = "voidphone-onion"
version = "0.1.0"
authors = ["Dominik Stolz <d.stolz@tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
