[package]
name = "voidphone-onion"
version = "0.1.0"
authors = ["Dominik Stolz <d.stolz@tum.de>"]
edition = "2018"

[lib]
name = "onion"

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
byteorder = "1.3.4"
anyhow = "1.0"