[onion]
api_address = "127.0.0.1:4200"
p2p_port = 4201
p2p_hostname = "127.0.0.1"
hostkey = "testkey.pem"
hops = 0

[rps]
peers = [
    { p2p_address = "127.0.0.1:4202", hostkey = "testkey.pem" },
    { p2p_address = "127.0.0.1:4203", hostkey = "testkey.pem" },
]
